#!/bin/sh

# thx Luke Smith
# Requires ffmpeg
# The timecode file need to have the timecodes and track titles separated with tab instead of space.
# TODO: Gör så att titeln inte blir lowercase och utan space efteråt. Om man skriver in titeln som t.ex. "Titel Ja" så blir det titel-ja. Kanske bara ändra kommandot som gör allting till lowercase och tar bort whitespace
# Gör ett miniskript som automatiskt skapar en codes.txt fil lol. Kanske cmdline option till detta skript
# Om det är ett / i ett av namnen i codes.txt så tar det det som en filsökväg lol
# Jobbigt om det  blir en error och man måste skriva om allting lol

[ ! -f "$2" ] && printf "The first file should be the audio, the second should be the timecodes.\\n" && exit

echo "Enter the album/book title:"; read -r booktitle
echo "Enter the artist/author:"; read -r author
echo "Enter the publication year:"; read -r year

inputaudio="$1"
ext="${1##*.}"

# Get a safe file name from the book.
#escbook="$(echo "$booktitle" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
escbook="$(echo "$booktitle")"

! mkdir -p "$escbook" &&
    echo "Do you have write access in this directory?" &&
    exit 1

# Get the total number of tracks from the number of lines.
total="$(wc -l < "$2")"

cmd="ffmpeg -i \"$inputaudio\" -nostdin -y"

while read -r x;
do
    end="$(echo "$x" | cut -d'	' -f1)"
    file="$escbook/$(printf "%.2d" "$track")-$esctitle.$ext"
    if [ -n "$start" ]; then
	cmd="$cmd -metadata artist=\"$author\" -metadata title=\"$title\" -metadata album=\"$booktitle\" -metadata year=\"$year\" -metadata track=\"$track\" -metadata total=\"$total\" -ss \"$start\" -to \"$end\" -vn -c:a copy \"$file\" "
    fi
    title="$(echo "$x" | cut -d'	' -f2-)"
    #esctitle="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
    esctitle="$(echo "$title")"
    track="$((track+1))"
    start="$end"
done < "$2"

# Last track must be added out of the loop.
file="$escbook/$(printf "%.2d" "$track")-$esctitle.$ext"
cmd="$cmd -metadata artist=\"$author\" -metadata title=\"$title\" -metadata album=\"$booktitle\" -metadata year=\"$year\" -metadata track=\"$track\" -ss \"$start\" -vn -c copy \"$file\""

eval "$cmd"
