#!/bin/sh

# A UI for detecting and selecting all displays. Probes xrandr for connected
# displays and lets user select one to use. User may also select "manual
# selection" which opens arandr.

mirror() {
    # Mirror displays using native resolution of external display and a scaled
    # version for the internal display
        external=$(echo "$screens" | dmenu -l 10 -h 38 -i -c -p "Optimize resolution for:")
        [ -z $external ] && exit || internal=$(echo "$screens" | grep -v "$external")

        res_external=$(xrandr --query | sed -n "/^$external/,/\+/p" | \
            tail -n 1 | awk '{print $1}')
        res_internal=$(xrandr --query | sed -n "/^$internal/,/\+/p" | \
            tail -n 1 | awk '{print $1}')

        res_ext_x=$(echo "$res_external" | sed 's/x.*//')
        res_ext_y=$(echo "$res_external" | sed 's/.*x//')
        res_int_x=$(echo "$res_internal" | sed 's/x.*//')
        res_int_y=$(echo "$res_internal" | sed 's/.*x//')

        scale_x=$(echo "$res_ext_x / $res_int_x" | bc -l)
        scale_y=$(echo "$res_ext_y / $res_int_y" | bc -l)

        xrandr --output "$external" --auto --scale 1.0x1.0 \
            --output "$internal" --auto --same-as "$external" \
            --scale "$scale_x"x"$scale_y"
}

twoscreen() { # If multi-monitor is selected and there are two screens.
        primary=$(echo "$screens" | dmenu -l 10 -h 38 -i -c -p "Select primary display:")
        [ -z $primary ] && exit || secondary=$(echo "$screens" | grep -v "$primary")
        direction=$(printf "left\\nright" | dmenu -l 10 -h 38 -i -c -p "What side of $primary should $secondary be on?")
        xrandr --output "$primary" --auto --scale 1.0x1.0 --output "$secondary" --"$direction"-of "$primary" --auto --scale 1.0x1.0
    }

morescreen() { # If multi-monitor is selected and there are more than two screens.
	primary=$(echo "$screens" | dmenu -l 10 -h 38 -i -c -p "Select primary display:")
	secondary=$(echo "$screens" | grep -v "$primary" | dmenu -l 10 -h 38 -i -c -p "Select secondary display:")
	direction=$(printf "left\\nright" | dmenu -l 10 -h 38 -i -c -p "What side of $primary should $secondary be on?")
	tertiary=$(echo "$screens" | grep -v "$primary" | grep -v "$secondary" | dmenu -l 10 -h 38 -i -c -p "Select third display:")
	xrandr --output "$primary" --auto --output "$secondary" --"$direction"-of "$primary" --auto --output "$tertiary" --"$(printf "left\\nright" | grep -v "$direction")"-of "$primary" --auto
	}

multimon() { # Multi-monitor handler.
	case "$(echo "$screens" | wc -l)" in
		2) twoscreen ;;
		*) morescreen ;;
	esac ;}

onescreen() { # If only one output available or chosen.
	xrandr --output "$1" --auto --scale 1.0x1.0 $(echo "$allposs" | grep -v "\b$1" | awk '{print "--output", $1, "--off"}' | paste -sd ' ' -)
	}

postrun() { # Stuff to run to clean up.
	xwallpaper --zoom ~/.local/share/wallpaper/*
	#xwallpaper --zoom "$(cat ~/.local/share/senastwallpaper)"
	keyboardconf		# Re-remap keys if keyboard added (for laptop bases)
	{ killall dunst ; setsid -f dunst ;} >/dev/null 2>&1 # Restart dunst to ensure proper location on screen
	}

laptopres() {
	chosen=$(printf "1920x1080\n1366x768\n" | dmenu)

	case $chosen in
		1920x1080) xrandr --output eDP-1 --scale-from 1920x1080 --panning 1920x1080 ;;
		1366x768) xrandr --output eDP-1 --scale-from 1366x768 --panning 1366x768 ;;
	esac
}


# Get all possible displays
allposs=$(xrandr -q | grep "connected")

# Get all connected screens.
screens=$(echo "$allposs" | awk '/ connected/ {print $1}')

# If there's only one screen
[ "$(echo "$screens" | wc -l)" -lt 2 ] &&
	#{ onescreen "$screens"; postrun; notify-send -t 2500 "💻 Only one screen detected..." ;  exit ;} #"using it in its optimal settings..." ;  exit ;}
	{ [ $(printf "Yes\nNo\n" | dmenu -i -p "Only one screen detected. Change screen resolution?") = Yes ] && laptopres ; postrun ; exit ;}
	#{ onescreen "$screens"; postrun; ltf ; postrun ; exit ;}

# Get user choice including multi-monitor and manual selection:
chosen=$(printf "%s\\nmulti-monitor\\nmirror displays\\nmanual selection\\nChange resuolution" "$screens" | dmenu -l 10 -h 38 -i -c -p "Select display arangement:") &&
case "$chosen" in
	"manual selection") arandr ; exit ;;
	"mirror displays") mirror ; exit ;;
	"multi-monitor") multimon ;;
	"Change resuolution") laptopres ;;
	*) onescreen "$chosen" ;;
esac

postrun
