#!/usr/bin/bash

# Volume notification: Pulseaudio and dunst
# inspired by gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a


icon_path=/usr/share/icons/Adwaita/64x64/status/
notify_id=506
sink_nr=1   # use `pactl list-sinks` to find out sink_nr


get_volume() {
    #pactl list-sinks | awk '/\tvolume:/ { print $5 }' | tail -n+$((sink_nr+1)) | head -n1 | cut -d '%' -f 1
    pactl -- get-sink-volume @DEFAULT_SINK@ | awk '{print $5}'
}

get_volume_icon() {
    if [ "$1" -lt 34 ];
    then
        echo -n "audio-volume-low-symbolic.symbolic.png"
    elif [ "$1" -lt 67 ];
    then
        echo -n "audio-volume-medium-symbolic.symbolic.png"
    elif [ "$1" -le 100 ];
    then
        echo -n "audio-volume-high-symbolic.symbolic.png"
    else
        echo -n "audio-volume-overamplified-symbolic.symbolic.png"
    fi
}

volume_notification() {
    volume=`get_volume`
    vol_icon=`get_volume_icon $volume`
    #bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')
    dunstify -t 2500 -r $notify_id -u low -i $icon_path$vol_icon $volume #$bar
}

mute_notification() {
	muted=$(pactl -- get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
    if [ $muted == 'yes' ]
    then
        dunstify -t 2500 -r $notify_id -u low -i ${icon_path}audio-volume-muted-symbolic.symbolic.png muted
    else
        dunstify -t 2500 -r $notify_id -u low -i ${icon_path}`get_volume_icon $(get_volume)` unmuted
    fi
}

case $1 in
    up)
	#pactl -- set-sink-volume @DEFAULT_SINK@ +5%
        volume_notification
        ;;
    down)
	#pactl -- set-sink-volume @DEFAULT_SINK@ -5%
        volume_notification
	    ;;
    mute)
	#pactl set-sink-mute @DEFAULT_SINK@ toggle
        mute_notification
        ;;
    *)
        echo "Usage: $0 up | down | mute"
        ;;
esac
