#!/bin/bash

lista=$(xinput --list | grep "Lenovo ThinkPad Compact USB Keyboard with TrackPoint.* pointer" | grep -o "id=..\?"  | grep "[0-9]" | sed 's/id=//g')

while read line
do
    echo "line: $lista"
done < <(ls -l)
