#!/bin/sh

#Få alla mountable enheter, en lista med alla mountpoints och mounta sedan den valda enheten vid den valda mountpointen.

[ -z "$(lsblk -lp | grep "part $")" ] && exit || device="$(lsblk -lp | grep "part $" | awk '{print " " $1 , "("$4")"}' | dmenu)" #vill få så att gigsen ($4) er i parantes

[ -z "$device" ] && exit || point="$(find /mnt /media /home -type d -maxdepth 3 2>/dev/null | dmenu)"

dev=$(echo $device | awk '{print $2}')

[ -z "$point" ] && exit || doas mount $dev $point && notify-send -t 2500 " $dev mounted on $point successfully"

#Göra så att man inte kan mounta på samma mountpoint
