#!/bin/sh

if [ $(cat /sys/class/net/wlan0/operstate) = up ]; then
	nmcli radio wifi off && sigdwmblocks 2 ; notify-send -t 3000 "Wifi disabled"
#	notify-send "Wifi disabled" && nmcli radio wifi off && sigdwmblocks 2 
elif [ $(cat /sys/class/net/wlan0/operstate) = down ]; then
	#notify-send "Wifi enabled" && nmcli radio wifi on && sigdwmblocks 2 
	nmcli radio wifi on && sigdwmblocks 2 ; notify-send -t 3000 "Wifi enabled" 
fi 
