#!/bin/sh

notify-send -t 2500 -i "$HOME/.local/share/icons/RSS-feed-logo-2017.png" "Updating feeds..." && newsboat -x reload && notify-send -t 2500 -i "$HOME/.local/share/icons/RSS-feed-logo-2017.png" "Feeds updated"
